# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

scaleio_nodes = [{:hostname => "node0", :ip => "192.168.33.50"}, {:hostname => "node1", :ip => "192.168.33.51"}, {:hostname => "node2", :ip => "192.168.33.52"}, {:hostname => "node3", :ip => "192.168.33.53"}, {:hostname => "node4", :ip => "192.168.33.54"}]
# vagrant box
vagrantbox="bento/centos-7.1"
vagrantboxurl="https://atlas.hashicorp.com/bento/boxes/centos-7.1/versions/2.2.2/providers/virtualbox.box"
# domain
domain = 'scaleio.local'



Vagrant.configure(2) do |config|
    scaleio_nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
      node_config.vm.box = "#{vagrantbox}"
      node_config.vm.box_url = "#{vagrantboxurl}"
      node_config.vm.host_name = "#{node[:hostname]}.#{domain}"
      node_config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "8192"]
      end
      node_config.vm.network "private_network", ip: "#{node[:ip]}", virtualbox__intnet: true
      node_config.vm.provision "shell", inline: 'setenforce  1 && echo "Removing useless bridge netfilters in /etc/sysctl.conf" && cp /etc/sysctl.conf /tmp/sysctl.conf && grep -v bridge /tmp/sysctl.conf > /etc/sysctl.conf && rm /tmp/sysctl.conf && cat  /etc/sysctl.conf && truncate -s 100GB /home/vagrant/scaleio1'
    end
  end
end
