---
- name: Install add-apt-repostory
  apt: name=software-properties-common state=latest

- name: Add Oracle Java Repository
  apt_repository:
    repo: "{{ scaleio_common_oracle_apt_repository }}"

- name: Accept Java 8 License
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8
  apt: name={{item}} state=latest
  with_items: scaleio_common_oracle_packages
